* Перформанс ревью

** Рассказал про polars

конец 2023

На DS семинаре в чт. показал работу с polars на примере аналитики спам звонков
Оставил ссылку на демо-репу с ифраструктурой для локального jupyter-server

** Диаграмма с чекерами
Конец 2023 Предложил использовать PlantUML для единообразия с командой
архитектуры.

Показал Ане и Паше диаграмму в Pycharm

Разобрался, как это публиковать в нашей Confluence wiki

Завёл задачу админам починить техническую проблему, из-за чего нельзя было
публиковать plantUML в нашей wiki

Апрель 2024 Админы сделали plantUML в вики
- [ ] Актуализировать по таблице чекеров и опубликовать диаграмму чекеров

** Метрики спама
Январь 2024

Оформил слои метаграфа
Оформил виджеты в дешборде

** Анина задача про скоринговую модель

Февраль 2024

Посодействовал качеству модели за счёт алгоритма автоматического перебора
комбинаций признаков.

** Задача про спам и премедиа
https://jira.sberned.ru/browse/NUDS-3743

Докопался до записей созвонов, выяснил что премедиа провоцирует робота на
преждевременный старт.

** Задача про evidently

апрель 2024

Ознакомился с туториалами бесплатного варианта evidently.
Заметил что бесплатная open-source часть очень далека от полноценного
ML-трекера. Предложенные в туториалах варианты, это proof-of-concept, который
скорее всего придётся дорабатывать.

Озвучил беспокойство, что не стоит работать над proof-of-concept без понимания,
- готовы ли мы будем его дорабатывать
- либо покупать платную версию
- либо надежды, что дорабатывать много не придётся

Dev-ы в итоге решили всё равно это дело пробовать, но уже без меня.

Выглядит конечно плохо для меня, как будто я упирался, и спорил, вместо того,
чтобы просто помочь.

Но мне кажется это их (dev, Алина) проблема, что они не смогли внятно
сформулировать или донести свою позицию.

Достаточно было сказать, например:
- Мы сделаем этот proof-of-concept, и почувствуем, много ли пользы в принципе
  от трекания качества модели в проде. А там будет видно.

А по факту не было даже прямого общения с ними, только какой-то испорченный
телефон через форвардинг сообщений в телеграме.

** Задача про спам-ботов
Заранее оценил возможный эффект на детекцию спама
апрель 2024 Сделал кастомный проект tagme на разметку аудио-ботов


** Рассказал про polars

конец 2023

На DS семинаре в чт. показал работу с polars на примере аналитики спам звонков
Оставил ссылку на демо-репу с ифраструктурой для локального jupyter-server

** Диаграмма с чекерами
Конец 2023 Предложил использовать PlantUML для единообразия с командой
архитектуры.

Показал Ане и Паше диаграмму в Pycharm

Разобрался, как это публиковать в нашей Confluence wiki

Завёл задачу админам починить техническую проблему, из-за чего нельзя было
публиковать plantUML в нашей wiki

Апрель 2024 Админы сделали plantUML в вики
- [ ] Актуализировать по таблице чекеров и опубликовать диаграмму чекеров

** Метрики спама
Январь 2024

Оформил слои метаграфа
Оформил виджеты в дешборде

** Анина задача про скоринговую модель

Февраль 2024

Посодействовал качеству модели за счёт алгоритма автоматического перебора
комбинаций признаков.

** Задача про спам и премедиа
https://jira.sberned.ru/browse/NUDS-3743

Докопался до записей созвонов, выяснил что премедиа провоцирует робота на
преждевременный старт.

** Задача про evidently

апрель 2024

Ознакомился с туториалами бесплатного варианта evidently.
Заметил что бесплатная open-source часть очень далека от полноценного
ML-трекера. Предложенные в туториалах варианты, это proof-of-concept, который
скорее всего придётся дорабатывать.

Озвучил беспокойство, что не стоит работать над proof-of-concept без понимания,
- готовы ли мы будем его дорабатывать
- либо покупать платную версию
- либо надежды, что дорабатывать много не придётся

Dev-ы в итоге решили всё равно это дело пробовать, но уже без меня.

Выглядит конечно плохо для меня, как будто я упирался, и спорил, вместо того,
чтобы просто помочь.

Но мне кажется это их (dev, Алина) проблема, что они не смогли внятно
сформулировать или донести свою позицию.

Достаточно было сказать, например:
- Мы сделаем этот proof-of-concept, и почувствуем, много ли пользы в принципе
  от трекания качества модели в проде. А там будет видно.

А по факту не было даже прямого общения с ними, только какой-то испорченный
телефон через форвардинг сообщений в телеграме.

** Задача про спам-ботов
Заранее оценил возможный эффект на детекцию спама
апрель 2024 Сделал кастомный проект tagme на разметку аудио-ботов
