* Работа с фото витрины

** Прод

Сервис offers_photos_moderation, 3 чекера в проде

photo_memes_checker
photo_watermark_checker
photo_obj_cls_checker

Сервис тащит фотографии для чекеров по url, напр
https://img.dmclk.ru/vitrina/46/78/4678bddda001c9828a3c0d88b2a13c0dc0106750_DS.webp

Это SberCloudCDN

** Обучение

* Датасет memes_img
  Картинки скопированы
  http://mleco.stat.sberned.ru/dataset/301/version/3/files

* Датасет watermarks_img
  Картинки скопированы
  http://mleco.stat.sberned.ru/dataset/291
* Датасет transact_photos_eva_and_offers
  http://mleco.stat.sberned.ru/dataset/183/version/16/files
  картинки скопированы

---

Mleco-CLI как стандартный формат для исследования по подбору и обучению модели

В mleco-CLI нет блокнотов

Сценарии где нужны блокноты:
- Аналитческая задача
- Начальный этап исследования, знакомство с технологией

- REPL - максимально ускоренная обратная связь
- 2 автоматическая привязка вывода к запросу

Показать на примере звуковой дорожки

Проблемы блокнотов:
- Не хватает воспроизводимости версий библиотек
- Затруднённое версионирование
- Затруднённое переиспользование кода
- Длинные блокноты
- Однопоточность

---
- [ ] След задачу на разметку заносим в новый инструмент tags
- [ ] Ставить тикеты в сообщения коммитов AF

---
- [ ] испробовать лемматизатор mystem

- [x] Eli5
    Библиотека eli5 используется для анализа и интерпретации результатов
    моделей машинного обучения. Она работает с такими библиотеками, как:
    Scikit-learn, XGBoost, CatBoost, Keras, lightning и LightGBM.

    Попробовал, для lightgbm просто выводит feature_importance по критерию
    gain, что проще сделать средствами самого lightgbm

    Есть фича подстветки текста красным / зелёным, что может быть полезно
    для NLP моделей.

    Есть фича интерпретации отдельного предсказания, что может быть полезно.

* Перформанс ревью

** Рассказал про polars
На DS семинаре в чт. показал работу с polars на примере аналитики спам звонков
Оставил ссылку на демо-репу с ифраструктурой для локального jupyter-server


** Диаграмма с чекерами
PlantUML
TODO боротьба тривае

** Метрики спама
Метаграф
TODO боротьба тривае

** Задача про спам и премедиа
https://jira.sberned.ru/browse/NUDS-3743

Докопался до записей созвонов, выяснил что премедиа провоцирует робота на
преждевременный старт.

