
- [ ] Взять август сентябрь

- Кластера
  - Покрытие
  - Проверябельность, посмотреть все доки кластера
  - Разделить спам не спам

- Сделал Саше Гридневу скрипт про звонки без b-части когда включали premedia
- https://wiki.sberned.ru/pages/viewpage.action?pageId=153208412
- Разобрался почему не сходятся метрики у меня и Ани в модели типа недвижимости
- По категоризации не продвинулся, только начал задавать вопросы, где взять
  бертопик.

---
- [ ] След задачу на разметку заносим в новый инструмент tags
- [ ] Ставить тикеты в сообщения коммитов AF
- [ ] В разметке созвонов писать роли Покупатель: Продавец:, сейчас 1: 2:

---
- [ ] испробовать лемматизатор mystem

- [x] Eli5
    Библиотека eli5 используется для анализа и интерпретации результатов
    моделей машинного обучения. Она работает с такими библиотеками, как:
    Scikit-learn, XGBoost, CatBoost, Keras, lightning и LightGBM.

    Попробовал, для lightgbm просто выводит feature_importance по критерию
    gain, что проще сделать средствами самого lightgbm

    Есть фича подстветки текста красным / зелёным, что может быть полезно
    для NLP моделей.

    Есть фича интерпретации отдельного предсказания, что может быть полезно.

* Перформанс ревью

** Рассказал про polars
На DS семинаре в чт. показал работу с polars на примере аналитики спам звонков
Оставил ссылку на демо-репу с ифраструктурой для локального jupyter-server


** Диаграмма с чекерами
PlantUML
TODO боротьба тривае

** Метрики спама
Метаграф
TODO боротьба тривае

** Задача про спам и премедиа
https://jira.sberned.ru/browse/NUDS-3743

Докопался до записей созвонов, выяснил что премедиа провоцирует робота на
преждевременный старт.

