* Проблемы wayland

** Спец флаги для совместимости nvidia и Wayland

Пришлось вручную писать флаг в /boot/

** Тормоза в Art of Rally

В X11 игра отключает compositor, что проявляется в отключении эффектов
прозрачности на рабочем столе. В wayland фокус не срабатывает.
Судя по форумам это баг драйвера NVidia

** Нет багфикса для Alt + Shift
шорткаты типа M-S-1 сломаны, т.к. в середине M-S переключает раскладку и
обрывает последовательность

** Браузер vivaldi нужно запускать со спец. флагами

--enable-features=UseOzonePlatform --ozone-platform=wayland --use-cmd-decoder=validating --use-gl=desktop

** Артефакты
в окнах Steam и JetBrainsToolbox

** Ненадёжное срабатывание Meta
Для вызова KRunner

** Застревание мышки между экранами
Курсор как бы слегка цепляется за границу между экранами

** Драйверы планшета
xsetwacom не работает в wayland

В отличие от X11 планшет можно почти настроить в штатном окне настроек планшета,
но из за валидации, привязка вертикальной координаты не идеальна, в нижней части
экрана курсор будет чуть выше чем нужно.

